spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientID: Iv1.2982c539dff21598
            clientSecret: 632c665c50d916b0d08950a180a1f90300444b97
          google:
            clientID: 504219030031-fgo3mu200427tn60fuhi25k12ecbjdfd.apps.googleusercontent.com
            clientSecret: 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
server:
  port: 8080
  hostname: localhost